import { Geist, Geist_Mono } from "next/font/google";
import { Gabarito } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const gabarito = Gabarito({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify needed weights
  variable: '--font-gabarito', // Optional: for Tailwind
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} antialiased bg-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
